// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_nnnltORg_jOtAeltGB9um_VCvRfDJSE',
    appId: '1:507611260353:android:f8efa02d11c2cf80d33b40',
    messagingSenderId: '507611260353',
    projectId: 'bhumijoauth',
    databaseURL: 'https://bhumijoauth-default-rtdb.firebaseio.com',
    storageBucket: 'bhumijoauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLRr9NjUOKLxy0yfTsbZENzbh1-5TQapk',
    appId: '1:507611260353:ios:0c9d02fb33e060c1d33b40',
    messagingSenderId: '507611260353',
    projectId: 'bhumijoauth',
    databaseURL: 'https://bhumijoauth-default-rtdb.firebaseio.com',
    storageBucket: 'bhumijoauth.firebasestorage.app',
    androidClientId: '507611260353-0b0012g2956qia3cpvha8jok7uqi04pu.apps.googleusercontent.com',
    iosBundleId: 'com.bhumijo.facilityapp',
  );
}
